<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1f6b5f6c-3a6d-4f1a-9c9d-2f0a5a7c8f10</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="SendGrid" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JobTracker.Application\JobTracker.Application.csproj" />
    <ProjectReference Include="..\JobTracker.Jobs.IntegrationEvents\JobTracker.Jobs.IntegrationEvents.csproj" />
    <ProjectReference Include="..\JobTracker.Persistence\JobTracker.Persistence.csproj" />
  </ItemGroup>

</Project>
